blank_issues_enabled: false
contact_links:
  - name: Shelly Fluxer
    url: https://fluxer.gg/vOjrMXcE
    about: Chat with the community for general questions and support.
  - name: Shelly's Site
    url: https://www.seafoam-labs.org/
    about: Our site with documentation and more.
 